services:

  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
    volumes:
      - db-data:/var/lib/postgresql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  localstack:
    image: localstack/localstack:3.0.2
    container_name: localstack
    ports:
      - "4566:4566"            # LocalStack Gateway
    environment:
      - SERVICES=s3
      - DEBUG=0
      - DATA_DIR=/tmp/localstack/data
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "./init-localstack.sh:/etc/localstack/init/ready.d/init-localstack.sh"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  s3-ui:
    image: cloudlena/s3manager:latest
    container_name: s3-ui
    ports:
      - "8090:8080"
    environment:
      - ENDPOINT=localstack:4566
      - ACCESS_KEY_ID=test
      - SECRET_ACCESS_KEY=test
      - REGION=us-east-1
      - USE_SSL=false
      - FORCE_PATH_STYLE=true
    depends_on:
      localstack:
        condition: service_healthy

volumes:
  db-data: