CREATE TABLE files (
    id UUID PRIMARY KEY,
    item_id UUID,
    filename VARCHAR(1000) NOT NULL,
    url_s3 VARCHAR(1000) NOT NULL,
    size BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

