ALTER TABLE address
    ADD COLUMN cep VARCHAR NOT NULL,
    ADD COLUMN number VARCHAR NOT NULL,
    ADD COLUMN address VARCHAR NOT NULL,
    ADD COLUMN complement VARCHAR NULL,
    ADD COLUMN neighborhood VARCHAR NOT NULL,
    ADD COLUMN city VARCHAR NOT NULL,
    ADD COLUMN state VARCHAR NOT NULL;

ALTER TABLE address DROP COLUMN name;
ALTER TABLE address DROP COLUMN place;


